[workspace]
name = "FastTrackCovariance"
channels = ["conda-forge"]
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.12,<3.13"
root = ">=6.32"
cxx-compiler = "*"
numpy = "*"
uproot = "*"
matplotlib = "*"
scikit-optimize = ">=0.10"
botorch = ">=0.12"
pytorch = ">=2.4"

[tasks]
optimize = "python optimizer.py"
baseline = "python test_baseline.py"
short-run = "python test_short_run.py"
